//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentaAutomoviles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Abono
    {
        public int IdAbono { get; set; }
        public int IdPago { get; set; }
        public int IdCredito { get; set; }
    
        public virtual Credito Credito { get; set; }
        public virtual Pago Pago { get; set; }
    }
}
