//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentaAutomoviles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpleadoFabrica
    {
        public int IdEmpleadoFabrica { get; set; }
        public int IdFabrica { get; set; }
        public int IdTipoEmpleadoFabrica { get; set; }
        public int IdDireccion { get; set; }
        public string Nombre { get; set; }
        public string Cedula { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }
    
        public virtual Direccion Direccion { get; set; }
        public virtual Fabrica Fabrica { get; set; }
        public virtual TipoEmpleadoFabrica TipoEmpleadoFabrica { get; set; }
    }
}
