//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentaAutomoviles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExtrasPorAutomovil
    {
        public int IdExtraAutomovil { get; set; }
        public int IdAutomovil { get; set; }
        public int IdExtra { get; set; }
        public int Cantidad { get; set; }
    
        public virtual Automovil Automovil { get; set; }
        public virtual Extra Extra { get; set; }
    }
}
