//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentaAutomoviles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Factura()
        {
            this.DetallePorFactura = new HashSet<DetallePorFactura>();
        }
    
        public int IdFactura { get; set; }
        public int IdEmpleadoSucursal { get; set; }
        public int IdSucursal { get; set; }
        public int IdCliente { get; set; }
        public decimal Monto { get; set; }
        public double Descuento { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallePorFactura> DetallePorFactura { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual Sucursal Sucursal { get; set; }
    }
}
